AllCops:
# some standard excludes. 
# we shouldn't be adding much to this on a project basis
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/deploy.rb'
    - 'config/deploy/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding StyleGuideCopsOnly, or by giving
  # the --only-guide-cops option.
  StyleGuideCopsOnly: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 150

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Description: "Keeps track of empty lines around class bodies."
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

# this makes breaking up chained method calls across lines pretty much impossible
# otherwise it would be a useful check https://github.com/bbatsov/rubocop/issues/1633
Style/MultilineOperationIndentation:
  Enabled: false

# Controversial!!
Metrics/LineLength:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# enabling this makes defining named scopes pretty awkward
# but I could be convinced to put it back in (sv)
Style/Lambda:
  Enabled: false

# this check is just too crude, I think, but I could be convinced otherwise (sv)
Style/BlockDelimiters:
  Enabled: false

# a little more forgiving in cucumber steps
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/**/*'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'features/step_definitions/**/*'

Lint/Void:
  Exclude:
    - 'features/step_definitions/**/*'

# DSLs that use blocks are easier to read if this whitespace is allowed
Style/EmptyLinesAroundBlockBody:
 Exclude:
  - 'spec/**/*'
  - 'lib/tasks/**/*'
  - 'lib/capistrano/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/spec_helper.rb'

# no ActiveSupport in cukes
Rails/TimeZone:
  Exclude:
    - 'features/**/*'
