on: [push]

name: Check site links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://tgaff.github.io/lzguides
          cmd_params: "--max-connections=3 --color=always"  # Check just one page
