name: Validate site links

on:
  deployment

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          args: "--verbose --no-progress './**/*.rst' https://labzero.com"
